import type {
  Capability,
  CoachPlan,
  CoachStep,
  LearningGuide,
  LearningResource,
  Note,
  UserProfile,
} from '../types/domain';
import {
  COACH_AGENT_PROMPT,
  generateCoachStepDetail,
  getLearningPath,
  type LearningStage,
} from './agent-prompts';
import { formatResourcesAsMarkdown, searchLearningResources } from './mcp-integration';

export async function generateCoachPlan({
  capabilities,
  notes,
  targetCapabilityId,
  userProfile,
}: {
  capabilities: Capability[];
  notes: Note[];
  targetCapabilityId?: string;
  userProfile: UserProfile;
}): Promise<CoachPlan> {
  const targetCapability = selectTargetCapability(capabilities, targetCapabilityId);
  const strongestCapability = capabilities.slice().sort((a, b) => b.progress - a.progress)[0];
  const stage = getStageFromProgress(targetCapability.progress);
  const learningPath = getLearningPath(targetCapability.id, stage);
  const resources = await searchLearningResources(targetCapability.id, {
    capability: targetCapability,
    focusArea: userProfile.focusArea,
    limit: 8,
  });
  const learningGuide = buildLearningGuide({
    targetCapability,
    strongestCapability,
    stage,
    learningPath,
    resources,
    notes,
    userProfile,
  });

  return {
    description: buildPlanDescription(targetCapability, strongestCapability, stage, userProfile),
    steps: buildCoachSteps(learningGuide, targetCapability, strongestCapability, stage, userProfile),
    learningGuide,
  };
}

export function getCapabilityNextPrompts(capabilityId: string): string[] {
  const templates = COACH_AGENT_PROMPT.nextPromptTemplates;
  return templates[capabilityId as keyof typeof templates] ?? templates.default;
}

export function formatStepAsMarkdown(step: CoachStep): string {
  return `## ${step.title}

${step.detail}

---
`;
}

export function exportPlanAsMarkdown(plan: CoachPlan): string {
  const resourceSection = plan.learningGuide
    ? `## Recommended Resources

${formatResourcesAsMarkdown(plan.learningGuide.resources)}

## Capture Template

\`\`\`markdown
${plan.learningGuide.captureTemplate}
\`\`\`
`
    : '';

  return `# ${stripMarkdown(plan.description)}

${plan.steps.map(formatStepAsMarkdown).join('\n')}

${resourceSection}
---
Generated by Coach Agent | PM Growth OS`;
}

function selectTargetCapability(capabilities: Capability[], targetCapabilityId?: string) {
  const sortedByGap = capabilities.slice().sort((a, b) => a.progress - b.progress);
  const fallback = sortedByGap[0] ?? capabilities[0];
  return capabilities.find((capability) => capability.id === targetCapabilityId) ?? fallback;
}

function getStageFromProgress(progress: number): LearningStage {
  if (progress < 34) return 'foundational';
  if (progress < 67) return 'advancing';
  return 'mastery';
}

function buildLearningGuide({
  targetCapability,
  strongestCapability,
  stage,
  learningPath,
  resources,
  notes,
  userProfile,
}: {
  targetCapability: Capability;
  strongestCapability: Capability;
  stage: LearningStage;
  learningPath: string[];
  resources: LearningResource[];
  notes: Note[];
  userProfile: UserProfile;
}): LearningGuide {
  const recentSignal = notes[0]?.tags[0] ?? userProfile.focusArea;
  const concept = getConcept(targetCapability.id, targetCapability.name);
  const practiceTask = [
    `Run a 30-minute ${targetCapability.name} practice using ${userProfile.focusArea} as the working scenario.`,
    'Pick one resource, extract one usable pattern, test it on a real PM artifact, and record the result.',
  ].join(' ');
  const captureTemplate = [
    `## ${targetCapability.name} Evidence`,
    '',
    `### Scenario`,
    `I practiced ${targetCapability.name} in the context of ${userProfile.focusArea}.`,
    '',
    '### Resource Used',
    '[Paste the resource title and link]',
    '',
    '### Pattern Tested',
    '[What idea, prompt, workflow, or evaluation method did you try?]',
    '',
    '### Result',
    '[What changed in output quality, clarity, speed, or confidence?]',
    '',
    '### Next Iteration',
    '[What will you test next?]',
  ].join('\n');

  return {
    capabilityId: targetCapability.id,
    capabilityName: targetCapability.name,
    concept,
    whyNow: [
      `${targetCapability.name} is currently at ${targetCapability.progress}% in the ${stage} stage, so a focused learning loop can create visible progress this week.`,
      `Your strongest adjacent capability is ${strongestCapability.name}; use that confidence to reduce friction.`,
      `Recent signal: ${recentSignal}.`,
    ].join(' '),
    learningPath,
    resources,
    practiceTask,
    reflectionPrompt: `After the practice, write one sentence about what became clearer, one sentence about what still feels uncertain, and one next experiment for ${targetCapability.name}.`,
    captureTemplate,
    nextStep: `Turn the practice result into one evidence note, then regenerate the Coach plan to pick the next smallest step.`,
  };
}

function buildCoachSteps(
  guide: LearningGuide,
  targetCapability: Capability,
  strongestCapability: Capability,
  stage: LearningStage,
  userProfile: UserProfile,
): CoachStep[] {
  const stageDetail = generateCoachStepDetail({
    capabilityName: targetCapability.name,
    stage,
    focusArea: userProfile.focusArea,
  });
  const topResources = guide.resources.slice(0, 4);

  return [
    {
      id: 'learn',
      title: 'Learn: understand the concept',
      detail: [
        guide.concept,
        '',
        `Why now: ${guide.whyNow}`,
        '',
        'Learning path:',
        ...guide.learningPath.map((item, index) => `${index + 1}. ${item}`),
      ].join('\n'),
      status: 'active',
    },
    {
      id: 'practice',
      title: 'Practice: run one focused exercise',
      detail: [
        guide.practiceTask,
        '',
        stageDetail,
        '',
        `Borrow confidence from ${strongestCapability.name}, your strongest adjacent capability at ${strongestCapability.progress}%.`,
      ].join('\n'),
      status: 'todo',
    },
    {
      id: 'capture',
      title: 'Capture: save evidence to Growth Map',
      detail: [
        'Use this template after the practice:',
        '',
        '```markdown',
        guide.captureTemplate,
        '```',
      ].join('\n'),
      status: 'todo',
    },
    {
      id: 'reflect',
      title: 'Reflect: decide the next iteration',
      detail: [
        guide.reflectionPrompt,
        '',
        `Next step: ${guide.nextStep}`,
      ].join('\n'),
      status: 'todo',
    },
    {
      id: 'resources',
      title: 'Resources: choose what to read first',
      detail: [
        'Start with one resource, not all of them. The goal is to convert reading into practice.',
        '',
        ...topResources.map(
          (resource, index) =>
            `${index + 1}. ${resource.title} (${resource.resourceType}) - ${resource.summary}`,
        ),
      ].join('\n'),
      status: 'todo',
    },
  ];
}

function buildPlanDescription(
  targetCapability: Capability,
  strongestCapability: Capability,
  stage: LearningStage,
  userProfile: UserProfile,
) {
  return [
    `**${targetCapability.name} learning sprint**`,
    `You are in the ${stage} stage for this capability. This plan turns Web Search into a Knowledge Tool: learn one idea, practice it in ${userProfile.focusArea}, capture evidence, then reflect.`,
    `Use ${strongestCapability.name} as leverage because it is currently your strongest adjacent capability.`,
  ].join('\n\n');
}

function getConcept(capabilityId: string, capabilityName: string) {
  const conceptMap: Record<string, string> = {
    'prompt-engineering':
      'Prompt engineering is the practice of shaping instructions, context, examples, and constraints so model output becomes more reliable and useful.',
    'context-engineering':
      'Context engineering is the practice of deciding what information an AI system should receive, remember, retrieve, summarize, or ignore.',
    'agent-design':
      'Agent design is the practice of defining roles, tools, handoffs, state, and review points so AI workflows can act reliably over multiple steps.',
    'ai-evaluation':
      'AI evaluation is the practice of measuring output quality, risk, cost, and reliability so product teams can improve AI systems deliberately.',
  };

  return conceptMap[capabilityId] ?? `${capabilityName} is a growth capability that improves when learning, practice, capture, and reflection stay connected.`;
}

function stripMarkdown(value: string) {
  return value.replace(/\*\*/g, '');
}

export default {
  generateCoachPlan,
  getCapabilityNextPrompts,
  formatStepAsMarkdown,
  exportPlanAsMarkdown,
};
