import type {
  Capability,
  CoachPlan,
  CoachStep,
  LearningGuide,
  LearningPracticeTask,
  LearningReview,
  LearningResource,
  Note,
  UserProfile,
} from '../types/domain';
import {
  COACH_AGENT_PROMPT,
  generateCoachStepDetail,
  getLearningPath,
  type LearningStage,
} from './agent-prompts';
import { formatResourcesAsMarkdown, searchLearningResources } from './mcp-integration';

export async function generateCoachPlan({
  capabilities,
  notes,
  targetCapabilityId,
  userProfile,
}: {
  capabilities: Capability[];
  notes: Note[];
  targetCapabilityId?: string;
  userProfile: UserProfile;
}): Promise<CoachPlan> {
  const targetCapability = selectTargetCapability(capabilities, targetCapabilityId);
  const strongestCapability = capabilities.slice().sort((a, b) => b.progress - a.progress)[0];
  const stage = getStageFromProgress(targetCapability.progress);
  const learningPath = getLearningPath(targetCapability.id, stage);
  const resources = await loadLearningResources(targetCapability, userProfile);
  const learningGuide = buildLearningGuide({
    targetCapability,
    strongestCapability,
    stage,
    learningPath,
    resources,
    notes,
    userProfile,
  });

  return {
    description: buildPlanDescription(targetCapability, strongestCapability, stage, userProfile),
    steps: buildCoachSteps(learningGuide, targetCapability, strongestCapability, stage, userProfile),
    learningGuide,
  };
}

async function loadLearningResources(
  targetCapability: Capability,
  userProfile: UserProfile,
): Promise<LearningResource[]> {
  try {
    return await searchLearningResources(targetCapability.id, {
      capability: targetCapability,
      focusArea: userProfile.focusArea,
      limit: 12,
    });
  } catch {
    return [];
  }
}

export function getCapabilityNextPrompts(capabilityId: string): string[] {
  const templates = COACH_AGENT_PROMPT.nextPromptTemplates;
  return templates[capabilityId as keyof typeof templates] ?? templates.default;
}

export function formatStepAsMarkdown(step: CoachStep): string {
  return `## ${step.title}

${step.detail}

---
`;
}

export function exportPlanAsMarkdown(plan: CoachPlan): string {
  const resourceSection = plan.learningGuide
    ? `## Recommended Resources

${formatResourcesAsMarkdown(plan.learningGuide.resources)}

## Evidence Template

\`\`\`markdown
${plan.learningGuide.captureTemplate}
\`\`\`
`
    : '';

  return `# ${stripMarkdown(plan.description)}

${plan.steps.map(formatStepAsMarkdown).join('\n')}

${resourceSection}
---
Generated by Coach Agent | PM Growth OS`;
}

function selectTargetCapability(capabilities: Capability[], targetCapabilityId?: string) {
  const sortedByGap = capabilities.slice().sort((a, b) => a.progress - b.progress);
  const fallback = sortedByGap[0] ?? capabilities[0];
  return capabilities.find((capability) => capability.id === targetCapabilityId) ?? fallback;
}

function getStageFromProgress(progress: number): LearningStage {
  if (progress < 34) return 'foundational';
  if (progress < 67) return 'advancing';
  return 'mastery';
}

function buildLearningGuide({
  targetCapability,
  strongestCapability,
  stage,
  learningPath,
  resources,
  notes,
  userProfile,
}: {
  targetCapability: Capability;
  strongestCapability: Capability;
  stage: LearningStage;
  learningPath: string[];
  resources: LearningResource[];
  notes: Note[];
  userProfile: UserProfile;
}): LearningGuide {
  const recentSignal = notes[0]?.tags[0] ?? userProfile.focusArea;
  const concept = getConcept(targetCapability.id, targetCapability.name);
  const practiceTasks = buildPracticeTasks(targetCapability, userProfile, resources);
  const practiceTask = formatPracticeTask(practiceTasks[0]);
  const captureTemplate = [
    `## ${targetCapability.name} Evidence`,
    '',
    `### Scenario`,
    `I practiced ${targetCapability.name} in the context of ${userProfile.focusArea}.`,
    '',
    '### Resource Used',
    '[Paste the resource title and link]',
    '',
    '### Pattern Tested',
    '[What idea, prompt, workflow, or evaluation method did you try?]',
    '',
    '### Result',
    '[What changed in output quality, clarity, speed, or confidence?]',
    '',
    '### Next Iteration',
    '[What will you test next?]',
  ].join('\n');
  const review = reviewLearningGuide({
    captureTemplate,
    learningPath,
    practiceTask,
    resources,
    targetCapability,
  });

  return {
    capabilityId: targetCapability.id,
    capabilityName: targetCapability.name,
    concept,
    whyNow: [
      `${targetCapability.name} is currently at ${targetCapability.progress}% in the ${stage} stage, so a focused learning loop can create visible progress this week.`,
      `Your strongest adjacent capability is ${strongestCapability.name}; use that confidence to reduce friction.`,
      `Recent signal: ${recentSignal}.`,
    ].join(' '),
    learningPath,
    resources,
    practiceTask,
    practiceTasks,
    reflectionPrompt: `After the practice, write one sentence about what became clearer, one sentence about what still feels uncertain, and one next experiment for ${targetCapability.name}.`,
    captureTemplate,
    nextStep: `Turn the practice result into one evidence record, then regenerate the Coach plan to pick the next smallest step.`,
    review,
  };
}

function reviewLearningGuide({
  captureTemplate,
  learningPath,
  practiceTask,
  resources,
  targetCapability,
}: {
  captureTemplate: string;
  learningPath: string[];
  practiceTask: string;
  resources: LearningResource[];
  targetCapability: Capability;
}): LearningReview {
  const hasRelevantResources = resources.some((resource) =>
    [resource.title, resource.summary, resource.whyUseful]
      .join(' ')
      .toLowerCase()
      .includes(targetCapability.name.toLowerCase().split(' ')[0]),
  );
  const hasToolGuidance = /Recommended tool:/i.test(practiceTask);
  const hasWorkingArtifact = /Working artifact:/i.test(practiceTask);
  const hasEvidenceOutput = /Output to save as evidence:/i.test(practiceTask);
  const evidenceTemplateIsDistinct =
    captureTemplate.includes('### Result') &&
    captureTemplate.includes('### Next Iteration') &&
    !captureTemplate.includes('Recommended tool:');
  const hasLearningLoop =
    learningPath.length >= 3 &&
    /Steps:/i.test(practiceTask) &&
    captureTemplate.includes('### Pattern Tested');

  const checks = [
    {
      label: 'Resource fit',
      passed: resources.length === 0 || hasRelevantResources,
      note:
        resources.length === 0
          ? 'Live resources are unavailable, so the task uses the capability playbook fallback.'
          : hasRelevantResources
            ? 'At least one resource appears connected to the selected capability.'
            : 'Resources may be too generic; prefer official docs, a tutorial, or a concrete case study.',
    },
    {
      label: 'Tool guidance',
      passed: hasToolGuidance,
      note: hasToolGuidance
        ? 'The task names a concrete tool or tool category to use.'
        : 'The task should name a concrete tool before the user starts.',
    },
    {
      label: 'Real artifact',
      passed: hasWorkingArtifact,
      note: hasWorkingArtifact
        ? 'The task asks for a real PM artifact instead of abstract practice.'
        : 'The task needs a specific artifact such as a PRD, user story, rubric, or workflow map.',
    },
    {
      label: 'Evidence output',
      passed: hasEvidenceOutput,
      note: hasEvidenceOutput
        ? 'The task defines what should be saved as evidence.'
        : 'The task should specify the final evidence artifact.',
    },
    {
      label: 'No duplicate Evidence step',
      passed: evidenceTemplateIsDistinct,
      note: evidenceTemplateIsDistinct
        ? 'The Evidence step captures results and reflection instead of repeating the Practice task.'
        : 'The Evidence step should be a recording template, not another practice instruction.',
    },
    {
      label: 'Learning loop',
      passed: hasLearningLoop,
      note: hasLearningLoop
        ? 'The plan connects learning, practice, evidence, and reflection.'
        : 'The plan needs a clearer Learn -> Practice -> Evidence -> Reflect sequence.',
    },
  ];
  const passedCount = checks.filter((check) => check.passed).length;
  const score = Math.round((passedCount / checks.length) * 100);
  const recommendations = checks
    .filter((check) => !check.passed)
    .map((check) => check.note)
    .slice(0, 3);

  if (recommendations.length === 0) {
    recommendations.push('Start with one resource, complete the practice once, then save the result as evidence.');
  }

  return {
    score,
    verdict: score >= 80 ? 'ready' : 'needs_improvement',
    checks,
    recommendations,
  };
}

function buildPracticeTasks(
  targetCapability: Capability,
  userProfile: UserProfile,
  resources: LearningResource[],
): LearningPracticeTask[] {
  const primaryResource = resources[0];
  const resourceLine = primaryResource
    ? `Recommended resource: ${primaryResource.title} (${primaryResource.url})`
    : 'Recommended resource: use the first official or tutorial resource that appears in Learning Resources.';
  const playbook = getPracticePlaybook(targetCapability.id, userProfile.focusArea);
  const resourceTitle = primaryResource?.title ?? 'the most relevant Learning Resource';

  return [
    {
      id: `${targetCapability.id}-calibration`,
      title: `Task 1: Calibrate the pattern`,
      objective: `Extract one reusable ${targetCapability.name} pattern from ${resourceTitle} and test it on a small PM artifact.`,
      tool: playbook.tool,
      artifact: playbook.artifact,
      steps: [
        resourceLine,
        'Pick one specific idea, checklist, prompt pattern, workflow step, or evaluation criterion from the resource.',
        ...playbook.steps.slice(0, 3),
        'Write a 3-line finding: what changed, why it changed, and when to reuse the pattern.',
      ],
      output: `Pattern note, small before/after test, and one reusable rule. ${playbook.output}`,
      doneWhen: playbook.doneWhen,
      estimatedMinutes: 25,
    },
    {
      id: `${targetCapability.id}-application`,
      title: `Task 2: Apply it to a real workflow`,
      objective: `Use the pattern in a real ${userProfile.focusArea} workflow and produce a PM-ready artifact.`,
      tool: playbook.tool,
      artifact: playbook.artifact,
      steps: [
        'Choose one real work scenario from this week, not a toy example.',
        ...playbook.steps,
        'Rewrite the final result so it could be shared with a teammate or stakeholder.',
      ],
      output: `A polished PM artifact plus the exact method used to create it. ${playbook.output}`,
      doneWhen: 'The artifact is useful enough to reuse, share, or compare against your normal workflow.',
      estimatedMinutes: 45,
    },
    {
      id: `${targetCapability.id}-evaluation`,
      title: `Task 3: Validate quality and next iteration`,
      objective: `Check whether the practice actually improved quality, speed, or confidence.`,
      tool: 'Google Sheets/Excel, a Markdown checklist, and one AI chat as a reviewer.',
      artifact: `The output from Task 1 or Task 2 for ${targetCapability.name}.`,
      steps: [
        'Define 3 quality criteria before judging the result.',
        'Score the baseline and improved result against those criteria.',
        'Ask an AI reviewer to critique the improved result and identify one hidden risk.',
        'Decide one next iteration: keep, revise, or discard the pattern.',
      ],
      output: 'Quality checklist, score comparison, reviewer critique, and next-iteration decision.',
      doneWhen: 'You can explain whether the method was actually better, not just different.',
      estimatedMinutes: 20,
    },
  ];
}

function formatPracticeTask(task: LearningPracticeTask) {
  return [
    `${task.estimatedMinutes}-minute ${task.title}`,
    '',
    `Objective: ${task.objective}`,
    `Recommended tool: ${task.tool}`,
    `Working artifact: ${task.artifact}`,
    '',
    'Steps:',
    ...task.steps.map((step, index) => `${index + 1}. ${step}`),
    '',
    `Output to save as evidence: ${task.output}`,
    `Done when: ${task.doneWhen}`,
  ].join('\n');
}

function getPracticePlaybook(capabilityId: string, focusArea: string) {
  const playbooks: Record<
    string,
    {
      artifact: string;
      doneWhen: string;
      output: string;
      steps: string[];
      tool: string;
    }
  > = {
    'prompt-engineering': {
      tool: 'ChatGPT, Claude, or Codex chat. Use the same model for both baseline and improved attempts.',
      artifact: `A real PM artifact from ${focusArea}: PRD section, user story, discovery notes, launch message, or customer feedback summary.`,
      steps: [
        'Paste the artifact into the tool and ask for the target output using your normal prompt. Save this as the baseline.',
        'Open one learning resource and extract one prompt pattern, such as role + context + constraints + examples + output format.',
        'Rewrite the prompt using that pattern. Keep the source artifact unchanged.',
        'Run the improved prompt and compare it against the baseline on clarity, completeness, actionability, and hallucination risk.',
        'Copy the winning prompt, the better output, and one sentence explaining why it improved.',
      ],
      output:
        'Baseline prompt, improved prompt, before/after output comparison, and one reusable prompt pattern.',
      doneWhen:
        'You can explain exactly which prompt change improved the PM artifact and when you would reuse it.',
    },
    'ai-product-strategy': {
      tool: 'A strategy memo template, ChatGPT/Claude for critique, and a simple opportunity scoring sheet.',
      artifact: `One AI product opportunity from ${focusArea}: user pain, workflow bottleneck, support pattern, or unmet capability.`,
      steps: [
        'Write the user problem, current workaround, and why AI could change the experience.',
        'Score the opportunity on user value, technical feasibility, data availability, risk, and business leverage.',
        'Ask an AI reviewer to challenge the weakest assumption in the opportunity thesis.',
        'Rewrite the thesis as a one-page product bet with target user, job-to-be-done, success metric, and risk boundary.',
        'Decide whether this is a now, later, or no-bet opportunity.',
      ],
      output: 'Opportunity scorecard, challenged assumption, and one-page AI product bet memo.',
      doneWhen: 'The product bet clearly explains why AI is needed and what evidence would validate it.',
    },
    'user-research-synthesis': {
      tool: 'Dovetail, Notion, Airtable, or a spreadsheet plus ChatGPT/Claude for clustering and counterexample review.',
      artifact: `A small research set from ${focusArea}: interview notes, feedback snippets, support tickets, sales notes, or app reviews.`,
      steps: [
        'Collect 8-12 raw user signals and preserve source labels.',
        'Ask AI to cluster the signals into themes, but require direct supporting quotes or snippets.',
        'Identify one counterexample or minority signal that does not fit the main theme.',
        'Turn the strongest theme into an opportunity statement and one product question.',
        'Save the theme, evidence snippets, counterexample, and decision implication.',
      ],
      output: 'Research synthesis board with themes, supporting evidence, counterexample, and product implication.',
      doneWhen: 'Each insight can be traced back to real source evidence rather than AI summary alone.',
    },
    'context-engineering': {
      tool: 'ChatGPT, Claude, or a Markdown editor plus an AI chat for testing context packets.',
      artifact: `A messy context source from ${focusArea}: meeting notes, long chat, PRD draft, research snippets, or backlog comments.`,
      steps: [
        'Choose one task the model should perform, such as summarize risks, draft a decision memo, or extract requirements.',
        'Create a context packet with four sections: goal, known facts, constraints, and source excerpts.',
        'Run the task once with the messy source and once with the structured context packet.',
        'Compare whether the structured packet reduced missing details, irrelevant details, or wrong assumptions.',
        'Save the reusable context packet structure and one example output.',
      ],
      output:
        'Messy context, structured context packet, output comparison, and a reusable context template.',
      doneWhen:
        'The structured packet produces a more reliable answer with less noise than the raw context.',
    },
    'rag-knowledge-systems': {
      tool: 'A docs folder or Notion database, a spreadsheet for source inventory, and ChatGPT/Claude for retrieval test design.',
      artifact: `A knowledge base from ${focusArea}: docs, PRDs, FAQs, help articles, research notes, or policy pages.`,
      steps: [
        'Inventory 10-20 sources and label freshness, authority, audience, and risk level.',
        'Create five realistic user questions that require grounded answers.',
        'For each question, identify which sources should be retrieved and which should be ignored.',
        'Draft a retrieval quality checklist covering source relevance, citation, conflict handling, and stale content.',
        'Run one manual retrieval test and record where grounding would fail.',
      ],
      output: 'Source inventory, retrieval test set, grounding checklist, and one failure analysis.',
      doneWhen: 'You can explain which sources should ground answers and which retrieval failure is most dangerous.',
    },
    'agent-design': {
      tool: 'Mermaid, Whimsical, Miro, FigJam, or a simple Markdown flowchart with ChatGPT/Claude as reviewer.',
      artifact: `One repeatable workflow from ${focusArea}: research synthesis, PRD drafting, feedback triage, release planning, or metric review.`,
      steps: [
        'Write the workflow goal and the final artifact the agent should produce.',
        'Map the workflow as steps with role, input, tool, output, and human review point for each step.',
        'Identify one step that should not be autonomous and add an explicit approval checkpoint.',
        'Ask an AI reviewer to find missing state, unclear handoffs, and failure modes.',
        'Revise the workflow and save the final map plus the top three failure modes.',
      ],
      output:
        'Agent workflow map, tool boundaries, handoff artifacts, review checkpoints, and failure modes.',
      doneWhen:
        'Another PM could follow the workflow without asking what the agent should do next.',
    },
    'tool-orchestration': {
      tool: 'Mermaid, Postman, Zapier/Make/n8n, or a simple API contract document with AI reviewer support.',
      artifact: `One tool-using workflow from ${focusArea}: search, database lookup, ticket creation, analytics query, or document update.`,
      steps: [
        'Define the user goal and the exact tool calls needed to complete it.',
        'Write a contract for each tool: input, output, permission, failure mode, and retry rule.',
        'Mark which tool calls need human approval and which can be automatic.',
        'Ask AI to find missing permissions, ambiguous inputs, and unsafe failure paths.',
        'Revise the orchestration flow with fallback behavior and audit logging.',
      ],
      output: 'Tool orchestration map, tool contracts, approval gates, and failure handling notes.',
      doneWhen: 'The workflow can fail safely without silently corrupting data or surprising the user.',
    },
    'ai-evaluation': {
      tool: 'Google Sheets/Excel plus ChatGPT/Claude for rubric drafting and output comparison.',
      artifact: `Three real or sample AI outputs from ${focusArea}, such as summaries, requirements, release notes, or support answers.`,
      steps: [
        'Define the job-to-be-done for the output and list what a good answer must include.',
        'Create a 5-point rubric with criteria for correctness, usefulness, specificity, risk, and tone.',
        'Score three outputs in a spreadsheet and add one sentence of evidence for each score.',
        'Ask an AI judge to score the same outputs using your rubric.',
        'Compare your scores with the AI judge and identify where the rubric needs clearer wording.',
      ],
      output:
        'Evaluation rubric, scored examples, disagreement notes, and one revised criterion.',
      doneWhen:
        'The rubric catches at least one quality difference that a vague preference would miss.',
    },
    'experimentation-metrics': {
      tool: 'Google Sheets/Excel, Amplitude/Mixpanel-style metric tree, and ChatGPT/Claude for metric critique.',
      artifact: `One AI feature or workflow from ${focusArea} that could be tested with users or offline examples.`,
      steps: [
        'Define the user behavior or product outcome the AI feature should improve.',
        'Choose one leading metric, one quality metric, one guardrail metric, and one cost metric.',
        'Create a minimum experiment plan with audience, baseline, treatment, sample, and decision rule.',
        'Ask AI to identify metric gaming, false positives, and missing guardrails.',
        'Revise the experiment plan and decide what evidence would justify continuing.',
      ],
      output: 'Metric tree, experiment plan, decision rule, and risk review.',
      doneWhen: 'The experiment can distinguish real user value from a nicer demo.',
    },
    'ai-safety-governance': {
      tool: 'Risk register, policy checklist, privacy review template, and ChatGPT/Claude as a red-team reviewer.',
      artifact: `One AI product scenario from ${focusArea} involving user data, automation, generated content, or decision support.`,
      steps: [
        'Describe the scenario, users affected, data used, and worst plausible harm.',
        'Classify risks across privacy, accuracy, bias, security, compliance, and user trust.',
        'Define prevention, detection, escalation, and user recovery controls.',
        'Ask AI to red-team the launch plan and identify one overlooked risk.',
        'Create a launch gate checklist for this scenario.',
      ],
      output: 'Risk register, mitigations, red-team finding, and launch gate checklist.',
      doneWhen: 'The launch decision has explicit risk boundaries and owner-approved mitigations.',
    },
    'automation-ops': {
      tool: 'Zapier, Make, n8n, GitHub Actions, or a Markdown runbook plus a monitoring checklist.',
      artifact: `One repeated PM workflow from ${focusArea}: reporting, triage, research intake, release notes, or stakeholder updates.`,
      steps: [
        'Map the manual workflow trigger, inputs, steps, output, owner, and failure symptoms.',
        'Identify which steps should be automated and which should stay human-reviewed.',
        'Design the automation with logging, rollback, alerting, and manual override.',
        'Run a dry test with sample inputs and record where it breaks.',
        'Write a lightweight runbook for operating and maintaining the automation.',
      ],
      output: 'Automation workflow map, ops checklist, dry-run result, and maintenance runbook.',
      doneWhen: 'The automation has an owner, failure path, and observable success criteria.',
    },
    'product-storytelling': {
      tool: 'Slide outline, Loom/script draft, release note template, and ChatGPT/Claude for audience critique.',
      artifact: `One AI product update from ${focusArea}: experiment result, feature launch, workflow improvement, or roadmap bet.`,
      steps: [
        'Define the audience and what decision or behavior the story should change.',
        'Draft a narrative with problem, insight, solution, proof, risk, and next ask.',
        'Create a short demo script or release note using concrete before/after evidence.',
        'Ask AI to critique clarity, credibility, specificity, and missing objections.',
        'Revise the story for one specific audience.',
      ],
      output: 'Audience-specific story, demo script or release note, critique, and revised version.',
      doneWhen: 'The story makes the AI value understandable without overclaiming what the system can do.',
    },
    'multi-agent-collaboration': {
      tool: 'Mermaid/FigJam for agent maps, prompt docs for role contracts, and ChatGPT/Claude as architecture reviewer.',
      artifact: `One multi-step PM workflow from ${focusArea} that needs specialist roles such as researcher, evaluator, writer, or reviewer.`,
      steps: [
        'Break the workflow into specialist agent roles and define each role objective.',
        'Specify handoff artifacts, memory needs, tool access, and review checkpoints.',
        'Identify where agents may disagree and how conflicts should be resolved.',
        'Ask AI to review the collaboration design for missing state, loops, and authority boundaries.',
        'Revise the design and mark what should be implemented first.',
      ],
      output: 'Multi-agent role map, handoff protocol, conflict rules, and first implementation slice.',
      doneWhen: 'The workflow has clear ownership, handoffs, review gates, and a safe first build step.',
    },
  };

  return playbooks[capabilityId] ?? playbooks['prompt-engineering'];
}

function buildCoachSteps(
  guide: LearningGuide,
  targetCapability: Capability,
  strongestCapability: Capability,
  stage: LearningStage,
  userProfile: UserProfile,
): CoachStep[] {
  const stageDetail = generateCoachStepDetail({
    capabilityName: targetCapability.name,
    stage,
    focusArea: userProfile.focusArea,
  });
  const topResources = guide.resources.slice(0, 4);
  const practiceTasks =
    guide.practiceTasks && guide.practiceTasks.length > 0
      ? guide.practiceTasks
      : [
          {
            id: 'legacy-practice',
            title: 'Practice: run one focused exercise',
            objective: guide.practiceTask,
            tool: 'AI chat or the tool recommended in the task.',
            artifact: `A real PM artifact from ${userProfile.focusArea}.`,
            steps: [guide.practiceTask],
            output: 'One evidence-ready practice result.',
            doneWhen: 'You can explain what improved and what to try next.',
            estimatedMinutes: 30,
          },
        ];

  return [
    {
      id: 'learn',
      title: 'Learn: understand the concept',
      detail: [
        guide.concept,
        '',
        `Why now: ${guide.whyNow}`,
        '',
        'Learning path:',
        ...guide.learningPath.map((item, index) => `${index + 1}. ${item}`),
      ].join('\n'),
      status: 'active',
    },
    ...practiceTasks.map((task, index) => ({
      id: `practice-${index + 1}`,
      title: task.title,
      detail: [
        formatPracticeTask(task),
        '',
        index === 0 ? stageDetail : '',
        '',
        `Borrow confidence from ${strongestCapability.name}, your strongest adjacent capability at ${strongestCapability.progress}%.`,
      ]
        .filter(Boolean)
        .join('\n'),
      status: 'todo' as const,
    })),
    {
      id: 'capture',
      title: 'Evidence: save progress to Growth Map',
      detail: [
        'Use this template after the practice:',
        '',
        '```markdown',
        guide.captureTemplate,
        '```',
      ].join('\n'),
      status: 'todo',
    },
    {
      id: 'reflect',
      title: 'Reflect: decide the next iteration',
      detail: [
        guide.reflectionPrompt,
        '',
        `Next step: ${guide.nextStep}`,
      ].join('\n'),
      status: 'todo',
    },
    {
      id: 'resources',
      title: 'Resources: choose what to read first',
      detail: [
        'Start with one resource, not all of them. The goal is to convert reading into practice.',
        '',
        ...topResources.map(
          (resource, index) =>
            `${index + 1}. ${resource.title} (${resource.resourceType}) - ${resource.summary}`,
        ),
      ].join('\n'),
      status: 'todo',
    },
  ];
}

function buildPlanDescription(
  targetCapability: Capability,
  strongestCapability: Capability,
  stage: LearningStage,
  userProfile: UserProfile,
) {
  return [
    `**${targetCapability.name} learning sprint**`,
    `You are in the ${stage} stage for this capability. This plan turns Web Search into a Knowledge Tool: learn one idea, practice it in ${userProfile.focusArea}, save evidence, then reflect.`,
    `Use ${strongestCapability.name} as leverage because it is currently your strongest adjacent capability.`,
  ].join('\n\n');
}

function getConcept(capabilityId: string, capabilityName: string) {
  const conceptMap: Record<string, string> = {
    'prompt-engineering':
      'Prompt engineering is the practice of shaping instructions, context, examples, and constraints so model output becomes more reliable and useful.',
    'ai-product-strategy':
      'AI product strategy is the practice of choosing valuable AI opportunities, defining the product bet, and connecting model capability to user outcomes.',
    'user-research-synthesis':
      'User research synthesis with AI is the practice of turning qualitative and behavioral signals into grounded insights, opportunity areas, and product decisions.',
    'context-engineering':
      'Context engineering is the practice of deciding what information an AI system should receive, remember, retrieve, summarize, or ignore.',
    'rag-knowledge-systems':
      'RAG and knowledge systems design is the practice of grounding AI output in trusted sources through retrieval, source quality, chunking, and citation workflows.',
    'agent-design':
      'Agent design is the practice of defining roles, tools, handoffs, state, and review points so AI workflows can act reliably over multiple steps.',
    'tool-orchestration':
      'Tool orchestration is the practice of deciding how AI systems call APIs, databases, search, and human review checkpoints to complete real work.',
    'ai-evaluation':
      'AI evaluation is the practice of measuring output quality, risk, cost, and reliability so product teams can improve AI systems deliberately.',
    'experimentation-metrics':
      'Experimentation and metrics for AI products is the practice of measuring whether AI features improve user outcomes, reliability, and business value.',
    'ai-safety-governance':
      'AI safety and governance is the practice of defining risk boundaries, policy constraints, privacy expectations, and launch gates for AI products.',
    'automation-ops':
      'Automation ops is the practice of turning repeated workflows into monitored, maintainable automations with fallback paths and clear ownership.',
    'product-storytelling':
      'Product storytelling is the practice of explaining AI product value through narratives, demos, release notes, adoption loops, and stakeholder updates.',
    'multi-agent-collaboration':
      'Multi-agent collaboration is the practice of coordinating specialist agents, handoffs, memory, review loops, and human approvals across complex workflows.',
  };

  return conceptMap[capabilityId] ?? `${capabilityName} is a growth capability that improves when learning, practice, evidence, and reflection stay connected.`;
}

function stripMarkdown(value: string) {
  return value.replace(/\*\*/g, '');
}

export default {
  generateCoachPlan,
  getCapabilityNextPrompts,
  formatStepAsMarkdown,
  exportPlanAsMarkdown,
};
